Domain/signIn
flow-build/studio-ddd pull request #1
Opened 2022-05-06 16:07 UTC by elsonfojr-fdte

- Absolute path added
- Ordering imports
- SignIn domain created
  - Hook to handle login created
  - Page created
  - Assets added
- Hook to handle api created
- Util to storage data on session storage created
- Theme created

2022-05-06 16:37 UTC, EduSantosBrito requested changes

2022-05-06 16:37 UTC, EduSantosBrito commented on src/core/components/Button/index.tsx
> +    onClick?: React.MouseEventHandler<HTMLButtonElement> | undefined;
```suggestion
    onClick?: React.MouseEventHandler<HTMLButtonElement>;
```

Quando a gente usa optional type, não há a necessidade de colocar `| undefined`

2022-05-06 16:37 UTC, EduSantosBrito commented on src/core/theme/globalStyle.ts
> +    max-height: 100vh; /* 100% do tamanho da tela */
Isso aqui pode dar problemas para responsividade futura (não sei se está no roadmap ser responsivo), só deixar isso anotado como ponto de observação

2022-05-06 16:37 UTC, EduSantosBrito commented on src/domain/signIn/config/types.ts
> +export type SignIn = {
Pode remover esse arquivo, não acho que faça sentido nesse domain

2022-05-06 16:37 UTC, EduSantosBrito commented on package.json
> +    "@emotion/react": "^11.9.0",
Pq emotion se no código estamos usando styled-components?

2022-05-09 14:35 UTC, elsonfojr-fdte commented on package.json
> +    "@emotion/react": "^11.9.0",
Removi a lib do styled components e estou utilizando a lib do emotion agora

2022-05-09 14:35 UTC, elsonfojr-fdte commented on src/domain/signIn/config/types.ts
> +export type SignIn = {
Removido

2022-05-09 14:36 UTC, elsonfojr-fdte commented on src/core/theme/globalStyle.ts
> +    max-height: 100vh; /* 100% do tamanho da tela */
Coloquei um comentário para sinalizar isso no código

2022-05-09 14:36 UTC, elsonfojr-fdte commented on src/core/components/Button/index.tsx
> +    onClick?: React.MouseEventHandler<HTMLButtonElement> | undefined;
Removi o undefined

2022-05-09 16:03 UTC, EduSantosBrito approved these changes

2022-05-09 16:29 UTC, merged